apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name:
  namespace:
spec:
  image:
  flinkVersion: v1_17
  flinkConfiguration:
   # scheduler-mode: REACTIVE
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: "3"
    restart-strategy.fixed-delay.delay: 10 s
    kubernetes.operator.job.restart.failed: "false"
    kubernetes.decorator.hadoop-conf-mount.enabled: "false"
    execution.attached: "true"
    high-availability.type: kubernetes
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    kubernetes.operator.jm-deployment-recovery.enabled: "false"
  serviceAccount:
  podTemplate:
    spec:
  jobManager:
    replicas: 1
    resource:
      memory:
      cpu: 1
  taskManager:
    resource:
      memory:
      cpu: 1
