apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: test-run
  namespace: flink-k8s-operator
spec:
  deploymentName: test-run-session
  job:
    args:
    - --sb
    - cuj
    entryClass: com.lakesoul.benchmark.TestSavepoint
    jarURI: local:///opt/flink/benchmarkTest-1.0-SNAPSHOT.jar
    parallelism: 2
    state: running
    upgradeMode: savepoint
